// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Finance.Data.Models
{
    [Table("BankAccount", Schema = "dbo")]
    public class BankAccount
    {
        public BankAccount()
        {
            Transactions = new HashSet<Transaction>();
        }

        [Key]
        public int BankAccountId { get; set; }
        [Required]
        public int CurrencyId { get; set; }
        [Required]
        [StringLength(20)]
        public string BankAccountName { get; set; }
        [Required]
        [Column(TypeName = "decimal(18, 2)")]
        public decimal BankAccountAmount { get; set; }
        [Required]
        [StringLength(255)]
        public string CreatedBy { get; set; }
        [Required]
        public DateTime CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        [StringLength(255)]
        public string UpdatedBy { get; set; }
        public bool IsDeleted { get; set; } = false;
        public int UserDetailId { get; set; }

        [ForeignKey("CurrencyId")]
        [InverseProperty("BankAccounts")]
        public Currency Currency { get; set; }

        [ForeignKey("UserDetailId")]
        [InverseProperty("BankAccounts")]
        public UserDetail UserDetail { get; set; }
        [InverseProperty("BankAccount")]
        public ICollection<Transaction> Transactions { get; set; }
    }
}