// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Finance.Data.Models
{
    [Table("Currency", Schema = "dbo")]
    public class Currency
    {
        public Currency()
        {
            BankAccounts =  new HashSet<BankAccount>();
            Loans =         new HashSet<Loan>();
            UserDetails = new HashSet<UserDetail>();
        }

        [Key]
        public int CurrencyId { get; set; }
        [Required]
        [StringLength(20)]
        public string CurrencyName { get; set; }
        public bool IsPopular { get; set; } = false;

        [InverseProperty("Currency")]
        public ICollection<BankAccount> BankAccounts { get; set; }
        [InverseProperty("Currency")]
        public ICollection<Loan> Loans { get; set; }
        [ForeignKey("CurrencyId")]
        [InverseProperty("Currencies")]
        public ICollection<UserDetail> UserDetails { get; set; }
    }
}