// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Finance.Data.Models
{
    [Table("LoanStatus", Schema = "dbo")]
    public class LoanStatus
    {
        public LoanStatus()
        {
            Loans =  new HashSet<Loan>();
        }

        [Key]
        public int LoanStatusId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [InverseProperty("LoanStatus")]
        public ICollection<Loan> Loans { get; set; }
    }   
}