// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Finance.Data.Models
{
    [Table("Loan", Schema = "dbo")]
    public class Loan
    {
        public Loan()
        {
            Transactions = new HashSet<Transaction>();
        }

        [Key]
        public int LoanId { get; set; }
        [Required]
        public int CurrencyId { get; set; }
        [Required]
        [StringLength(500)]
        public string Note { get; set; }
        [Required]
        [StringLength(30)]
        public string Person { get; set; }
        [Required]
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Amount { get; set; }
        [Required]
        [StringLength(255)]
        public string CreatedBy { get; set; }
        [Required]
        public DateTime CreatedDate { get; set; }
        public DateTime? Deadline { get; set; }
        public DateTime? UpdatedDate { get; set; }
        [StringLength(255)]
        public string UpdatedBy { get; set; }
        public bool IsDeleted { get; set; } = false;
        [Required]
        public int UserDetailId { get; set; }
        [StringLength(255)]
        [Unicode(false)]
        public string? ContactEmail { get; set; }
        public int? ContactDetailId { get; set; }
        [Required]
        public int LoanStatusId { get; set; }

        [ForeignKey("CurrencyId")]
        [InverseProperty("Loans")]
        public Currency Currency { get; set; }

        [ForeignKey("ContactDetailId")]
        [InverseProperty("LoanContactDetails")]
        public virtual UserDetail ContactDetail { get; set; }

        [ForeignKey("UserDetailId")]
        [InverseProperty("LoanUserDetails")]
        public virtual UserDetail UserDetail { get; set; }

        [ForeignKey("LoanStatusId")]
        [InverseProperty("Loans")]
        public LoanStatus LoanStatus { get; set; }

        [InverseProperty("Loan")]
        public ICollection<Transaction> Transactions { get; set; }
    }
}