// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Finance.Data.Models
{
    [Table("Transaction", Schema = "dbo")]
    public class Transaction
    {
        [Key]
        public int TransactionId { get; set; }
        [Required]
        [Column(TypeName = "decimal(18, 2)")]
        public decimal TransactionAmount { get; set; }
        [StringLength(255)] 
        public string? Notes { get; set; }
        [Required]
        public DateTime CreatedDate { get; set; }
        [Required]
        [StringLength(255)]
        public string CreatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        [StringLength(255)]
        public string UpdatedBy { get; set; }
        public int? BankAccountId { get; set; }
        public int? LoanId { get; set; }
        public bool IsDeleted { get; set; } = false;
        [StringLength(255)]
        public string QuoteOnStatus { get; set; }

        [ForeignKey("BankAccountId")]
        [InverseProperty("Transactions")]
        public BankAccount BankAccount { get; set; }

        [ForeignKey("LoanId")]
        [InverseProperty("Transactions")]
        public Loan Loan { get; set; }
    }
}